SQL exercises 1
ya-pekatoros/PostgreSQL-exercises pull request #2
Opened 2023-02-25 15:06 UTC by ya-pekatoros

2023-02-26 21:20 UTC, aleksandr-semenov-dbp requested changes

2023-02-26 21:20 UTC, aleksandr-semenov-dbp commented on QUERIES.sql
> +SELECT name, lastname from employees WHERE email NOT LIKE '%dualbootpartners.com';
К сожалению не выбираются сотрудники с пустыми (NULL) email-ами

2023-02-27 01:39 UTC, ya-pekatoros commented on QUERIES.sql
> +SELECT name, lastname from employees WHERE email NOT LIKE '%dualbootpartners.com';
Верно, сравнение LIKE с NULL дает NULL, исправил!

2023-03-04 09:50 UTC, aleksandr-semenov-dbp approved these changes

2023-03-04 11:20 UTC, merged